<!-- START of: finna - RecordDriver/DefaultRecord/record-3d-player.phtml -->
<script>
    window.addEventListener ('load', () => {
    // init all viewers on the page
    OV.Init3DViewerElements ();
});
</script>
<div class="online_3d_viewer"
    style="width: 800px; height: 600px;"
    model="model.obj, model.mtl">
</div>
<!-- END of: finna - RecordDriver/DefaultRecord/record-3d-player.phtml -->
