<?php
  $img = $this->recordImage($this->record($this->driver));
  $urls = $this->driver->tryMethod('getURLs');

  $hasImages = !empty($this->driver->tryMethod('getAllImages'));

  $hasVideos = !empty(array_filter(
      $this->driver->tryMethod('getURLs') ?? [],
      fn($url) => isset($url['embed']) && in_array($url['embed'], ['video', 'iframe'])
  ));

  $hasAudios = !empty(array_filter(
      $this->driver->tryMethod('getURLs') ?? [],
      fn($url) => isset($url['embed']) && $url['embed'] === 'audio'
  ));

  $hasModels = !empty($this->driver->tryMethod('getModels'));

  $digitalObjects = [$hasImages, $hasVideos, $hasAudios, $hasModels];

  $hasManyDigitalObjects = count(array_filter($digitalObjects, fn($value) => $value === true)) > 1;

?>

<div class="record-digital-object-full-width">
  <?php if ($hasManyDigitalObjects): ?>
    <ul class="nav nav-pills">
      <?php if ($hasImages): ?><li class="active"><a data-toggle="pill" href="#image"><?=$this->transEsc('Image')?></a></li><?php endif; ?>
      <?php if ($hasVideos): ?><li><a data-toggle="pill" href="#video"><?=$this->transEsc('Video')?></a></li><?php endif; ?>
      <?php if ($hasModels): ?><li><a data-toggle="pill" href="#3d"><?=$this->transEsc('3d')?></a></li><?php endif; ?>
      <?php if ($hasAudios): ?><li><a data-toggle="pill" href="#audio"><?=$this->transEsc('Audio')?></a></li><?php endif; ?>
    </ul>
    <div class="tab-content">
      <?php if ($hasImages): ?>
        <div id="image" class="tab-pane fade in active">
          <?=$this->record($this->driver)->renderTemplate('record-image-information.phtml', ['img' => $img]); ?>
        </div>
      <?php endif; ?>
      <?php if ($hasModels): ?>
        <?php
          $modelUrls = [];
          foreach ($this->record($this->driver)->getLinkDetails() as $url) {
            if (!empty($url['videoSources']) || !empty($url['embed']) && $url['embed'] == 'video' || $this->recordLinker()->getEmbeddedVideo($url['url']) == 'data-embed-iframe') {
              $modelUrls[] = $url;
            }
          }
        ?>
        <?php print_r($modelUrls) ?>
        <div id="3d" class="tab-pane fade">
          <?=$this->record($this->driver)->renderTemplate('record-3d-player.phtml');?>
        </div>
      <?php endif; ?>
      <?php if ($hasVideos): ?>
        <?php
          $videoUrls = [];
          foreach ($this->record($this->driver)->getLinkDetails() as $url) {
            if (!empty($url['videoSources']) || !empty($url['embed']) && $url['embed'] == 'video' || $this->recordLinker()->getEmbeddedVideo($url['url']) == 'data-embed-iframe') {
              $videoUrls[] = $url;
            }
          }
        ?>
        <div id="video" class="tab-pane fade">
          <div class="inline-video" id="inline-video"></div>
            <?=$this->record($this->driver)->renderTemplate('record-video-player.phtml', ['videoUrls' => $videoUrls, 'inlineVideo' => true]);?>
          </div>
        </div>
      <?php endif; ?>
      <?php if ($hasAudios): ?>
        <div id="audio" class="tab-pane fade">
          <h3>Menu 2</h3>
          <p>Some content in menu 2.</p>
        </div>
      <?php endif; ?>
    </div>
  <?php else: ?>
    <?php if ($hasImages): ?>
      <?=$this->record($this->driver)->renderTemplate('record-image-information.phtml', ['img' => $img]); ?>
    <?php endif; ?>
  <?php endif; ?>
</div>

